### ISSUE TITLE
Kartlegge og etablere verdikjedeovervåking

### ISSUE THREAD

**Issue by HanneLauritsen1967** [Altinn/kunde#18]
### Description

- Kartlegge sammen med produkteiere/Sjefsarkitekt - hvilke type verdikjeder vi bør ha
- Planlegge hva/hvordan vi kan overvåke disse 
- Etablere god rutiner for oppfølging av hendelser i verdikjedene (team må være proaktivt på og agere før feilsituasjoner skjer, eller minimerer konsekvenser).
- Opplæring, ansvar mm for håndtering av verdikjeder
- Dette bør etableres iløpet av 2025 (Punktet er også diskutert med Ronny Birkeli som understøtter dette at er viktig at kommer på plass)

**Comment by aas-tbuar** [comment]
Verdikjedeovervåkning er:
 - Brukerinteraksjon: Brukeren fyller ut et skjema eller forespørsel på Altinn-portalen.
 - Applikasjonslag: Forespørselen sendes til Altinn-applikasjonen, som behandler og validerer informasjonen.
 - Integrasjon med eksterne systemer: Tjenesten kan hente inn data fra eksterne systemer som Folkeregisteret eller Skatteetaten.
 - Databehandling og lagring: Data behandles og lagres midlertidig eller permanent i Altinns databaser.
 - Resultat og tilbakemelding: Sluttresultatet presenteres for brukeren, enten i form av et svar, et innsendingstoken, eller en annen form for bekreftelse.

Er dette noe som kundeteamet skal ha ansvar for? Dersom TE eier sine applikasjoner og drift av disse, skal vi da ha en overvåkning over hele sulamitten? @HanneLauritsen1967

**Comment by aas-tbuar** [comment]
Verdikjedeovervåkning skal skje på de respektive produktene. Det er ikke tenkt at Kundeteamet skal overvåke verdikjede/bruksmønster.
