### ISSUE TITLE
Revisjon av Bilag 3

### ISSUE THREAD

**Issue by HanneLauritsen1967** [Altinn/kunde#19]
### Description

- revidere bilag 3 
- Tilpasse bilag 3 
- Bilag 3 blir underlag til bruksvilkår
- revidert bilag 3 skal ut rundt okt 2024 og leve frem til bruksvilkår tar over
- Implementere revidert bilag 3 i organisasjonen

**Comment by HanneLauritsen1967** [comment]
Bilag 3 ble fremlagt ledergruppen 6.9 og godkjent. 
Vi skal ha en siste høring med produkteiere 20.9, deretter går det ut på høring til utvalgte tjenesteiere. 
Det ble på møtet 6.9 beslutte av vi også skal fremlegge tilleggstjenester til Bilag 3, som vi evt skal "selge" til våre tjenesteeiere og basert på dette må vi snarest starte prosessen med å rigge et teknisk støtte team.

**Comment by HanneLauritsen1967** [comment]
Det må også ses på en prismodell for tilleggstjenester når definisjon av dem er klar

**Comment by HanneLauritsen1967** [comment]
11.10: De som har svart på høringsdok av TE er, SSB, BRREG og moderniseringsprosjektet

**Comment by aas-tbuar** [comment]
Videre jobb med bilag 3 er stoppet  og erstattet av Bruksvilkår https://github.com/orgs/Altinn/projects/121/views/1?pane=issue&itemId=61965607&issue=Altinn%7Ckunde%7C14
